apiVersion: 1

deleteDatasources:
  - name: Jaeger
    orgId: 1

datasources:
  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
